name: CI BUILD for Docker Action

on:
  push:
    branches: [ main]
    paths: [ hello-wolrd-docker-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest 
    steps: 
      - name: Chekout
        uses: actions/checkout@v4

      - name: Run my own container action 
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@jumainfomagnus'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the actions said Hello"
      
